### ISSUE TITLE
Oracle database static password rotation not working

### ISSUE THREAD

**Issue by Dane903** [hashicorp/vault-plugin-database-oracle#126]
Hi all,
I'm setting up an Oracle database static password change process but am running into a requirement from Oracle that the current password be supplied at the time of the password change. The link [here](https://logbuffer.wordpress.com/2014/03/03/oracle-ora-28221-replace-not-specified-on-password-change/) explains it well.  

https://logbuffer.wordpress.com/2014/03/03/oracle-ora-28221-replace-not-specified-on-password-change/

**What is available in the Vault Oracle Plugin:** 
ALTER USER {{username}} IDENTIFIED BY "{{password}}"

**What is needed:**
ALTER USER {{username}} IDENTIFIED BY "{{password}}" REPLACE "{{current_password}}"

I did look into using a stored procedure for this:

create or replace procedure sys.update_user_password
( i_new_password in varchar2 )
AUTHID DEFINER
as
  v_current_user varchar2(128) := USER;
begin
  if v_current_user = 'MYUSER' then
    execute immediate 'alter user MYUSER' || ' identified by "' || i_new_password || '"';
  end if;
end update_user_password;
grant execute on sys.update_user_password to MYUSER;

and got it working but ran into an issue with calling "begin...proc name;end;" syntax due to not being able to determine how to set split_statements (https://github.com/hashicorp/vault-plugin-database-oracle/pull/62 ) to false. Even with the stored procedure approach we'd have to deploy the stored procedure to each database, which is a job in itself. 

At this point I'm thinking of editing the vault source to add the capability for the {{current_password}} variable and for it to be included in the oracle plugin as well. 
Is there anything security wise that would prevent this from being added? 
I think this would benefit anyone running Oracle with static password rotation and using PASSWORD_VERIFY_FUNCTION, which is pretty standard. 

Thank you

**Comment by fairclothjm** [comment]
@Dane903 Hello, you can use https://developer.hashicorp.com/vault/api-docs/secret/databases#rotation_statements to configure a custom rotation command. Please reopen this is you run into any issues. Thanks!
