### ISSUE TITLE
Is there support for multi-tenant usernames like c##{{name}}

### ISSUE THREAD

**Issue by cmeon** [hashicorp/vault-plugin-database-oracle#21]
Hello, I'd like help to configure the naming generation to prefix them with `c##` for oracle 12c multi tenant DBs.

**Comment by pcman312** [comment]
Currently there is no support for configuring the username generated for dynamic credentials. Usernames are created in the form:

`v_{display name}_{role name}_{20 random characters}_{unix timestamp}`

`{display name}` and `{role name}` are each truncated to 8 characters and the entire username is truncated to 30 characters. The random characters are limited to the regex `[a-zA-Z0-9]`. An example might be `v_dispname_rolename_ha98egryhz`

**Comment by pcman312** [comment]
Hi @cmeon ! I wanted to give an update on this. We've had a number of requests revolving around the idea of giving users the ability to customize how dynamic usernames are generated. In Vault 1.7 (coming soon) we are introducing the idea of `username_template` to some* of our secret engines. This will give the ability to fully customize how a username is generated prior to passing that username to the appropriate statements run in the database. Each engine will default to the current behavior, but this will allow for customization if that default does not suit their needs.

There will be docs available through https://www.vaultproject.io once 1.7 is released will describe this in more detail but I wanted to give you a heads up for this new feature coming soon!

<sub>* - engines supported in 1.7: PostgreSQL, MSSQL, MySQL, MongoDB (not MongoDB Atlas), Cassandra, Oracle, and OpenLDAP</sub>

**Comment by cmeon** [comment]
Sounds super. I had an outdated fork of this. I'm so glad it's coming out.
