### ISSUE TITLE
Add static account support

### ISSUE THREAD

**Issue by malnick** [hashicorp/vault-plugin-database-oracle#23]

**Comment by oravirt** [comment]
If you by this mean just rotating the password for an already existing user then yes!

**Comment by pcman312** [comment]
Support added in https://github.com/hashicorp/vault-plugin-database-oracle/pull/26

**Comment by kind-grape** [comment]
Hi @malnick @pcman312 I would assume the latest release of this plugin https://releases.hashicorp.com/vault-plugin-database-oracle/0.2.1/ would have included this?
Asking as I ran into an issue with static role creation https://github.com/hashicorp/vault-plugin-database-oracle/issues/38 and wondering if I am not doing it correctly.
Dynamic creds were created successfully using the same db configs
