### ISSUE TITLE
Vault compatibility

### ISSUE THREAD

**Issue by niclarcipretti** [hashicorp/vault-plugin-database-oracle#24]
Hi, 

Just wondering which versions of vault this plugin is compatible with?

I'm having the hardest time trying to set it up with vault 1.2.3 (tested with 1.3.0 too).

Any thoughts to share?

Cheers

Nikao

**Comment by niclarcipretti** [comment]
Just to clarify why I'm asking this: when I try to execute this plugin (version 0.1.6) with vault 1.3.0, the following error occurs:

```
Error writing data to database/config/sigtint: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/sigtint
Code: 400. Errors:

* error creating database object: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

**Comment by jefferai** [comment]
Can you look in your Vault logs? I believe there should be more information there related to why this is failing.

**Comment by niclarcipretti** [comment]
Hi @jefferai,

Nope, that's the only info available. Do you know if I can run vault with a "debug" log level?

**Comment by jefferai** [comment]
Sure, maybe even run it at trace level just in case anything more useful is there.

**Comment by niclarcipretti** [comment]
Well, I managed to solve the issue. 

There were 2 main problems:

1 - The Oracle's instant client used in the pre-compiled version of the plugin was 19, I was using 12. So I had to recompile the plugin for my version. I guess it would help a lot if this information was in the project's readme.md, don't you agree? I could help you guys with that!

2 - The plugin is incompatible with Linux Alpine out of the box (I didn't go much further, but I guess there's something to do with musl), and Vault's base docker image is alpine based. This info would help a lot too.

3 - Vault's default logging is just awckward. The messages I was receveing didn't help at all. I had to use a lot of SO cmds to get to the real problem, but what really helped was LDD). Trace level just helped after I solved all the issues above (pointing me to the fact that my config.json was lacking the app_addr conf)

Hope this helps someone in the future. Let me know if you need an extra hand to enrich the docs ;)

Cheers

**Comment by jefferai** [comment]
Hi there,

1) Yes, probably we should document the version of the instant client used with the current build. (Feel free to PR an update to the readme since you said you'd help :-)  )

2) I didn't know the plugin was incompatible with Alpine, although I guess it doesn't surprise me. Other plugins tend to work fine with Vault in Docker so it's likely something specific to linking against the instant client libs rather than Vault. Maybe also note this in the readme PR? :-)

3) I'm not sure what the issues are with logging are. Looking at the other issue linked above it seems like enabling trace level logging in Vault immediately pointed to the issue, so when you say you had to use SO and LDD I'm not sure why.

**Comment by niclarcipretti** [comment]
Hey @jefferai!

I'll do my best to work on the readme asap.

The trace log just helped after I sorted out everything else and got the plugin to run effectively. Before that, it only logged the "no such file or directory" message, that was being thrown by the SO. What we could do is pro actively discover more about the execution error and provide richer messages to the final user, can't we? I could help with this in the design level (I'm a software architect, but I'm no golang dev unfortunately, could try though).

**Comment by jefferai** [comment]
> What we could do is pro actively discover more about the execution error and provide richer messages to the final user, can't we
Honestly, I have no idea. I don't know whether the issue was the translation of the error coming out of the plugin or whether we simply didn't get a better error message from the underlying Go libs.

**Comment by pcman312** [comment]
Resolved with: https://github.com/hashicorp/vault-plugin-database-oracle/pull/25
