### ISSUE TITLE
Kill sessions in RAC aware manner

### ISSUE THREAD

**Issue by vt-ms** [hashicorp/vault-plugin-database-oracle#30]
The current implementation of the revoke logic uses the V$SESSION view to find sessions for the managed user that need to be terminated. Unfortunately, while this works well on a single instance database it does not account for a clustered configuration where the privileged vault user is not guaranteed to connect to the same node as the clients it manages.

As a remedy to this issue, I would like to suggest that the GV$SESSION view be used instead. This view provides a cluster-wide view into database sessions and exposes an additional column INST_ID to identify the cluster node that a session is using. With this information the ALTER SYSTEM KILL SESSION command may then take an additional argument to allow killing sessions across nodes e.g., `ALTER SYSTEM KILL SESSION '<sid>,<serial#>,@<inst_id>';`

The GV$SESSION view as well as the modified ALTER SYSTEM KILL SESSION command will work on both RAC and Single Instance database configurations.

**Comment by pcman312** [comment]
Fixed with #62
