### ISSUE TITLE
username length

### ISSUE THREAD

**Issue by mjtice** [hashicorp/vault-plugin-database-oracle#36]
I posted this in the mailing list - but maybe it's better posted here:

Hi guys, 

I've been using the Oracle vault plugin for a quite a while now and it's worked perfectly for what we need (so, thanks!).  

I do have some questions regarding the username length.

I know that currently the length of the username is capped at 30 characters [1] - but why was it set at 30?  Oracle changed the length of the underlying dictionary to 128 bytes in 12.1.0.1 [2], which was released in 2013 (previously it was 30 [3]).  And Oracle officially increased the length of the identifiers as a whole in 12.2.0.1 [4], which was released in 2018.  

Perhaps the limit of 30 was to accommodate those Oracle users that were using much older software?

What would be the optimal way of getting this changed in the plugin (yes, a PR :) ) - but I'm wondering ...  Should the constant be changed from 30 to something larger (maybe the max of 128)?  Or maybe adding another configuration option when configuring the connection [5]?  Something like 'max_username_length'? 

What does everyone think?

1. https://github.com/hashicorp/vault-plugin-database-oracle/blob/master/oracle.go#L24
2. https://docs.oracle.com/database/121/REFRN/GUID-309FCCB2-2E8D-4371-9FC5-7F3B10E2A8C0.htm#REFRN23302
3. https://docs.oracle.com/cd/E18283_01/server.112/e17110/statviews_5081.htm
4. https://docs.oracle.com/en/database/oracle/oracle-database/12.2/newft/new-features.html#GUID-64283AD6-0939-47B0-856E-5E9255D7246B
5. https://www.vaultproject.io/api/secret/databases/oracle#configure-connection

**Comment by pcman312** [comment]
Hi @mjtice ! I wanted to give an update on this. We've had a number of requests revolving around the idea of giving users the ability to customize how dynamic usernames are generated. In Vault 1.7 (coming soon) we are introducing the idea of `username_template` to some* of our secret engines. This will give the ability to fully customize how a username is generated prior to passing that username to the appropriate statements run in the database. Each engine will default to the current behavior, but this will allow for customization if that default does not suit their needs.

There will be docs available through https://www.vaultproject.io once 1.7 is released will describe this in more detail but I wanted to give you a heads up for this new feature coming soon!

<sub>* - engines supported in 1.7: PostgreSQL, MSSQL, MySQL, MongoDB (not MongoDB Atlas), Cassandra, Oracle, and OpenLDAP</sub>
