### ISSUE TITLE
Using vault-plugin-database-oracle with vault in one image 

### ISSUE THREAD

**Issue by cannondaleSL4** [hashicorp/vault-plugin-database-oracle#37]
Hi, 
could you help me with understanding what way is correct for using vault-plugin-database-oracle with vault in one image?
I use plugin - https://releases.hashicorp.com/vault-plugin-database-oracle/0.2.1
And i need to use oracle instantclient-basiclite - https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip
But as we know client instantclient-basiclite has some problem with glibs.
I have added https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc/blob/master/Dockerfile and it works, but i'am not sure it's correct way.

**Comment by fairclothjm** [comment]
@cannondaleSL4 An alternative could be to use an operating system that is supported by Oracle: https://github.com/oracle/docker-images/tree/main/OracleInstantClient
