### ISSUE TITLE
Static Role Creation Error

### ISSUE THREAD

**Issue by kind-grape** [hashicorp/vault-plugin-database-oracle#38]
Hi folks, I have created and configured the oracle db endpoint. Static role creation is not working. Dynamic roles/creds is working as expected on the other hand. 

Steps to reproduce
1. Create DB config based on db instance connection details
```
vault write db/$vault_db_path/config/$DB_name \
              plugin_name="vault-plugin-database-oracle" \
              connection_url="{{username}}/{{password}}@//$DB_host:$DB_port/$DB_name" \
              allowed_roles="*" \
              username="$DB_username" \
              password="$DB_password" \
              max_open_connections="$DB_max_open_connect" \
              max_connection_lifetime="$DB_max_connect_lifetime" \
```
2. Configure a db role to use dynamic creds 
```
vault write db/$vault_db_path/roles/$DB_dynamic_role \
              db_name=$DB_name \
              creation_statements="CREATE USER {{name}} IDENTIFIED BY {{password}}; GRANT CONNECT TO {{name}}; GRANT CREATE SESSION TO {{name}};ALTER USER $ALT_user GRANT CONNECT THROUGH {{name}};" \
              revocation_statements="REVOKE CONNECT FROM {{name}}; REVOKE CREATE SESSION FROM {{name}}; ALTER USER $ALT_user revoke CONNECT THROUGH {{name}}; DROP USER {{name}};" \
              default_ttl="5m" \
              max_ttl="2h"
```
3. Confirm dynamic creds/secret is working by reading 
```
vault read db/ora/creds/$DB_dynamic_role
Key                Value
---                -----
lease_id           db/ora/creds/*redacted*/*redacted*
lease_duration     5m
lease_renewable    true
password           *redacted*
username           *redacted*
```

4. Now when trying to create a static role where DB_username_2 is a username in the Oracle DB,  using the following command
```
vault write db/ora/static-roles/${DB_name}-static_role \
              db_name=$DB_name \
              username=$DB_username_2 \
              rotation_statements="ALTER USER {{username}} IDENTIFIED BY '{{password}}'" \
              rotation_period=10m
```
It will fail with the following error
```
Error writing data to db/ora/static-roles/*redacted*: Error making API request.

URL: PUT https://*redacted*/v1/db/ora/static-roles/*redacted*
Code: 500. Errors:

* 1 error occurred:
	* error setting credentials: rpc error: code = Unknown desc = rpc error: code = Unimplemented desc = Not yet implemented
```

Would like to hear more thought or if anyone has experience such issue

**Comment by kind-grape** [comment]
Following error from the trace log level output of the vault server

20.082-0400 [TRACE] secrets.database.database_1f0380d9.vault-plugin-database-oracle: initialize: transport=gRPC status=started
Aug 18 10:47:20 dev-tev-secretsmanagement-vault-i-06b284df0751bfb7e vault[26344]: 2020-08-18T10:47:20.722-0400 [TRACE] secrets.database.database_1f0380d9.vault-plugin-database-oracle: initialize: transport=gRPC status=finished verify=true err=<nil> took=639.622229ms
Aug 18 10:47:20 dev-tev-secretsmanagement-vault-i-06b284df0751bfb7e vault[26344]: 2020-08-18T10:47:20.722-0400 [TRACE] secrets.database.database_1f0380d9.vault-plugin-database-oracle: generate credentials: transport=gRPC status=started
Aug 18 10:47:20 dev-tev-secretsmanagement-vault-i-06b284df0751bfb7e vault[26344]: 2020-08-18T10:47:20.723-0400 [TRACE] secrets.database.database_1f0380d9.vault-plugin-database-oracle: generate credentials: transport=gRPC status=finished err=<nil> took=1.015255ms
Aug 18 10:47:20 dev-tev-secretsmanagement-vault-i-06b284df0751bfb7e vault[26344]: 2020-08-18T10:47:20.728-0400 [TRACE] secrets.database.database_1f0380d9.vault-plugin-database-oracle: set credentials: transport=gRPC status=started
Aug 18 10:47:20 dev-tev-secretsmanagement-vault-i-06b284df0751bfb7e vault[26344]: 2020-08-18T10:47:20.728-0400 [TRACE] secrets.database.database_1f0380d9.vault-plugin-database-oracle: set credentials: transport=gRPC status=finished err="rpc error: code = Unknown desc = rpc error: code = Unimplemented desc = Not yet implemented" took=527.598µs

Vault version: 1.3.2
Oracle DB version 
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

**Comment by pcman312** [comment]
Thanks for reaching out @kind-grape! This looks like you are using an older version of the plugin. Static credential rotation was added in v0.2.0.

**Comment by kind-grape** [comment]
Thanks @pcman312 for the replied. And I have confirmed by using the latest plugin 0.2.1 from the release page, I was able to get the static role creation working as expected!
```
$ vault write db/ora/static-roles/db-static_role \
>               db_name="db" \
>               username="static_name" \
>               rotation_period=10m
Success! Data written to: db/ora/static-roles/db-static_role
]$ vault list db/ora/static-roles/
Keys
----
db-static_role
]$ vault read db/ora/static-creds/db-static_role
Key                    Value
---                    -----
last_vault_rotation    2020-08-19T10:28:11.515640575-04:00
password               *redacted*
rotation_period        10m
ttl                    9m26s
username               STATIC_NAME
```

**Comment by kind-grape** [comment]
@pcman312 another follow up question is, if we were to create a static role with the same db username as the one we used in the db config 
```
vault write db/$vault_db_path/config/$DB_name \
              plugin_name="vault-plugin-database-oracle" \
              connection_url="{{username}}/{{password}}@//$DB_host:$DB_port/$DB_name" \
              allowed_roles="*" \
              username="$DB_username" \
              password="$DB_password" \
              max_open_connections="$DB_max_open_connect" \
              max_connection_lifetime="$DB_max_connect_lifetime" \
```

Would this new static role cred would be updated in the connection config accordingly? There is a rotate root which I think would work as such and we want to see if static role can be used in the rotate of the configured password. Given our scenarios, DBA would not give us the root credential (sys/system in oracle case) to us.

**Comment by pcman312** [comment]
@kind-grape Apologies for not responding sooner! I didn't get a notification for it :(

As for your question: no it will not. There isn't a mechanism for automatically rotating the root user's password on a cadence. If you were to set it up as a static user you would encounter two problems:

1) The roles under that database would no longer function as there isn't a connection between static roles and the root user itself. When the static role is created, it immediately rotates that user's password and any subsequent calls would fail because the root user's password stored in Vault does not match what's in the database.
2) The root user's password would be exposed by reading those credentials from `/static-creds/:name`. This is an exposure of credentials that we are explicitly preventing for the root user because the root user is very sensitive. Once the `/rotate-root` call is made, the credentials in the database are only known to Vault and Vault will not provide them to a caller via any request.
