### ISSUE TITLE
Recompile on OEL

### ISSUE THREAD

**Issue by dbasolved** [hashicorp/vault-plugin-database-oracle#40]
I've been trying to get this plugin to work with Oracle Instant Client 19.8.  I've updated the oci8.pc file with the following:

prefix=/opt/app/oracle/19.8.0/client_1
libdir=${prefix}
includedir=${prefix}/sdk/include

Name: oci
Description: Oracle database engine
Version: 19.1
Libs: -L${libdir} -lclntsh
Cflags: -I${includedir}

I've installed the Oracle Instant Client 19.8 on OEL 7.7.  Set the following environment variables:

ORACLE_BASE=/opt/app/oracle
ORACLE_HOME=/opt/app/oracle/19.8.0/client_1
LD_LIBRARY_PATH=/opt/app/oracle/19.8.0/client_1
PKG_CONFIG_PATH=/vagrant/ora_software/gocode
GOPATH=/vagrant/ora_software/gocode

When I run "go build -o vault-plugin-database-oracle ./plugin", the output that is generated produces some errors but proceeds:

[root@HashiCorpVault vault-plugin-database-oracle]# go build -o vault-plugin-database-oracle ./plugin

# github.com/hashicorp/vault-plugin-database-oracle/vendor/github.com/hashicorp/go-retryablehttp
vendor/github.com/hashicorp/go-retryablehttp/client.go:447:17: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
vendor/github.com/hashicorp/go-retryablehttp/client.go:507:16: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
vendor/github.com/hashicorp/go-retryablehttp/client.go:538:16: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
vendor/github.com/hashicorp/go-retryablehttp/client.go:545:15: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
vendor/github.com/hashicorp/go-retryablehttp/client.go:554:14: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
# github.com/hashicorp/vault-plugin-database-oracle/vendor/github.com/hashicorp/vault/sdk/helper/certutil
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:339:7: unknown field 'URIs' in struct literal of type x509.Certificate
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:396:94: in.URIs undefined (type *x509.Certificate has no field or method URIs)
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:519:7: unknown field 'URIs' in struct literal of type x509.Certificate
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:634:7: unknown field 'URIs' in struct literal of type x509.CertificateRequest
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:739:15: certTemplate.URIs undefined (type *x509.Certificate has no field or method URIs)
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:739:31: data.CSR.URIs undefined (type *x509.CertificateRequest has no field or method URIs)
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:751:15: certTemplate.URIs undefined (type *x509.Certificate has no field or method URIs)
vendor/github.com/hashicorp/vault/sdk/helper/certutil/types.go:758:63: undefined: x509.ExtKeyUsageMicrosoftCommercialCodeSigning
vendor/github.com/hashicorp/vault/sdk/helper/certutil/types.go:762:63: undefined: x509.ExtKeyUsageMicrosoftKernelCodeSigning
[root@HashiCorpVault vault-plugin-database-oracle]#

After this, I do "make test" and the build fails:

[root@HashiCorpVault vault-plugin-database-oracle]# make test

==> Checking that code complies with gofmt requirements...
go generate
CGO_ENABLED=1 go test -tags='' $(go list ./... | grep -v /vendor/ | grep -v /integ)  -timeout=20m -parallel=4
# github.com/hashicorp/vault-plugin-database-oracle/vendor/github.com/hashicorp/go-retryablehttp
vendor/github.com/hashicorp/go-retryablehttp/client.go:447:17: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
vendor/github.com/hashicorp/go-retryablehttp/client.go:507:16: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
vendor/github.com/hashicorp/go-retryablehttp/client.go:538:16: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
vendor/github.com/hashicorp/go-retryablehttp/client.go:545:15: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
vendor/github.com/hashicorp/go-retryablehttp/client.go:554:14: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
# github.com/hashicorp/vault-plugin-database-oracle/vendor/github.com/hashicorp/vault/sdk/helper/certutil
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:339:7: unknown field 'URIs' in struct literal of type x509.Certificate
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:396:94: in.URIs undefined (type *x509.Certificate has no field or method URIs)
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:519:7: unknown field 'URIs' in struct literal of type x509.Certificate
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:634:7: unknown field 'URIs' in struct literal of type x509.CertificateRequest
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:739:15: certTemplate.URIs undefined (type *x509.Certificate has no field or method URIs)
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:739:31: data.CSR.URIs undefined (type *x509.CertificateRequest has no field or method URIs)
vendor/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go:751:15: certTemplate.URIs undefined (type *x509.Certificate has no field or method URIs)
vendor/github.com/hashicorp/vault/sdk/helper/certutil/types.go:758:63: undefined: x509.ExtKeyUsageMicrosoftCommercialCodeSigning
vendor/github.com/hashicorp/vault/sdk/helper/certutil/types.go:762:63: undefined: x509.ExtKeyUsageMicrosoftKernelCodeSigning
FAIL	github.com/hashicorp/vault-plugin-database-oracle [build failed]
make: *** [test] Error 2
[root@HashiCorpVault vault-plugin-database-oracle]#

I obviously have something either misconfigured or out of place.  Is there any tips on what I've overlooked?

thanks

**Comment by pcman312** [comment]
Hi @dbasolved ! Apologies for not seeing this earlier.

This looks like you might be using an old version of Go. The version we use to build it is 1.14. If you upgrade to >=1.14 it should fix this issue.
