### ISSUE TITLE
Unrecognized Remote Plugin Message

### ISSUE THREAD

**Issue by BinaryWizard904** [hashicorp/vault-plugin-database-oracle#48]
I have been trying to get this plugin working in a docker instance for days now, but I haven't been able to establish a connection to my oracle database.  Instead I always receive the following error

> sh-4.2$ vault write sys/plugins/catalog/database/oracle-database-plugin sha256=$(sha256sum /vault/plugins/vault-plugin-database-oracle | awk '{print $1}') command="vault-plugin-database-oracle"
> Success! Data written to: sys/plugins/catalog/database/oracle-database-plugin
> sh-4.2$ vault secrets enable database
> Success! Enabled the database secrets engine at: database/
> sh-4.2$ vault write database/config/oracle-xe plugin_name=oracle-database-plugin allowed_roles="ora-xe-*" connection_url='{{username}}/{{password}}@//<server IP>/XEPDB1' username='system' password='RuinousSafety'
> Error writing data to database/config/oracle-xe: Error making API request.
> 
> URL: PUT http://127.0.0.1:8200/v1/database/config/oracle-xe
> Code: 400. Errors:
> 
> * error creating database object: invalid database version: 2 errors occurred:
>         * Unrecognized remote plugin message:
> 
> This usually means that the plugin is either invalid or simply
> needs to be recompiled to support the latest protocol.
>         * Unrecognized remote plugin message:
> 
> This usually means that the plugin is either invalid or simply
> needs to be recompiled to support the latest protocol.

I have done everything I can think of from installing various versions of the Oracle Instant Client 19 alongside the plugin to recompiling it for Instant Client v19.10, but nothing seems to work.  I double-checked that this wasn't an access issue or incorrect connection string before posting this.  I can successfully connect to the database from the same container using the same connection string via SQL*Plus.

I've attached a copy of the files I'm using to build the docker image so you can see for yourself.

**EDIT - 2021-02-24: Attachment updated and instructions added.**
[docker src files - vault + vault-plugin-database-oracle.zip](https://github.com/hashicorp/vault-plugin-database-oracle/files/6039085/docker.src.files.-.vault.%2B.vault-plugin-database-oracle.zip)

### Build Commands:
NOTE: This dockerfile uses a [multistage build](https://docs.docker.com/develop/develop-images/multistage-build/) to allow users to easily choose between the recompiled plugin included in the zip and the one in the official Hashicorp repo.
#### To Build The Image Using The Recompiled Vault Plugin Run:
`docker build --pull --rm -f 'Dockerfile' --target import-plugin -t oravault:latest-imp '.'`
#### To Build The Image Using The Hashicorp Release Of The Vault Plugin Run:
`docker build --pull --rm -f 'Dockerfile' --target download-plugin -t oravault:latest-down '.'`

### Run Command:
`docker run --cap-add=IPC_LOCK -p 8200:8200 -d oravault:latest-[imp|down]`

The list of commands I'm using to add the plugin to Vault and configure it can be found in the included "Add Oracle Plugin To Vault.txt" file.

**Comment by BinaryWizard904** [comment]
I tried creating a similar VM and it _worked_.  I can't figure out why.  What would cause this plugin to work under a VM but fail when run via docker?

**Comment by nouseforaname** [comment]
Have you checked ldd output on the plugin binary?
Maybe it is related to CGO?

**Comment by BinaryWizard904** [comment]
LDD output is consistent on both the VM and the Docker instance.  I've manually checked and both have all the files/synonyms in place.  Moreover, as I'm using oraclelinux as the base, OCI is installed via yum, which should cover dependency issues.

As for go, that isn't installed on either the docker instance or the VM running vault.  Going by the VM I got working it doesn't appear to be needed.

**Comment by pcman312** [comment]
Hi @BinaryWizard904 ! I'm looking into this and I think I've spotted a problem. In the files you attached you have a zip file which contains the Oracle plugin binary along with a SHA256 file associated with it. The SHA in that file matches the zip file, not the binary inside the zip file.

Regarding the Dockerfile: I have been unable to get it to run correctly so far. It looks like it might be in an interim development state and I haven't gotten it to run correctly.

**Comment by BinaryWizard904** [comment]
> Hi @BinaryWizard904 ! I'm looking into this and I think I've spotted a problem. In the files you attached you have a zip file which contains the Oracle plugin binary along with a SHA256 file associated with it. The SHA in that file matches the zip file, not the binary inside the zip file.
> 
> Regarding the Dockerfile: I have been unable to get it to run correctly so far. It looks like it might be in an interim development state and I haven't gotten it to run correctly.

The included SHA256 file is used to validate the zip file before unzipping it.  For the plugin file itself, the SHA256 hash is generated inline when adding the plugin to the vault, e.g.:
`vault write sys/plugins/catalog/database/oracle-database-plugin sha256=$(sha256sum /vault/plugins/vault-plugin-database-oracle | awk '{print $1}') command="vault-plugin-database-oracle"`

I tested and that should have worked, but just in case I'll update the files I attached with the latest working version I have and include the commands I use to build and run the containers.

**Comment by BinaryWizard904** [comment]
@pcman312 I've updated the OP to offer the latest version of the dockerfile I have.  I double-checked that this version builds and runs before posting.  I've also included the exact commands I use to build and run the container.

**Comment by mjtice** [comment]
What does the listener log show when a write attempt is made?  Also, if you enable `Trace` in the vault logging, what output is printed around the error?

**Comment by BinaryWizard904** [comment]
@mjtice 
Listener log shows:
```SystemVerilog
2021-04-05T21:06:02.617Z [INFO] secrets.database.database_802b9d71.oracle-database-plugin: configuring client automatic mTLS
2021-04-05T21:06:02.649Z [DEBUG] secrets.database.database_802b9d71.oracle-database-plugin: starting plugin: path=/vault/plugins/vault-plugin-database-oracle args=[/vault/plugins/vault-plugin-database-oracle]
2021-04-05T21:06:02.650Z [DEBUG] secrets.database.database_802b9d71.oracle-database-plugin: plugin started: path=/vault/plugins/vault-plugin-database-oracle pid=150
2021-04-05T21:06:02.650Z [DEBUG] secrets.database.database_802b9d71.oracle-database-plugin: waiting for RPC address: path=/vault/plugins/vault-plugin-database-oracle
2021-04-05T21:06:02.675Z [DEBUG] secrets.database.database_802b9d71.oracle-database-plugin: plugin process exited: path=/vault/plugins/vault-plugin-database-oracle pid=150 error="signal: killed"
2021-04-05T21:06:02.739Z [DEBUG] secrets.database.database_802b9d71.oracle-database-plugin: starting plugin: path=/vault/plugins/vault-plugin-database-oracle args=[/vault/plugins/vault-plugin-database-oracle]
2021-04-05T21:06:02.739Z [DEBUG] secrets.database.database_802b9d71.oracle-database-plugin: plugin started: path=/vault/plugins/vault-plugin-database-oracle pid=157
2021-04-05T21:06:02.740Z [DEBUG] secrets.database.database_802b9d71.oracle-database-plugin: waiting for RPC address: path=/vault/plugins/vault-plugin-database-oracle
2021-04-05T21:06:02.754Z [DEBUG] secrets.database.database_802b9d71.oracle-database-plugin: plugin process exited: path=/vault/plugins/vault-plugin-database-oracle pid=157 error="signal: killed"
```


If Vault logging is set to `trace`, attempting to configure an oracle database secret engine throws the following error:
>```
>Error writing data to database/config/oracle-xe: Error making API request.
>
>URL: PUT http://127.0.0.1:8200/v1/database/config/oracle-xe
>Code: 400. Errors:
>
>* error creating database object: invalid database version: 2 errors occurred:
>        * Unrecognized remote plugin message: cannot allocate memory
>
>This usually means that the plugin is either invalid or simply
>needs to be recompiled to support the latest protocol.
>        * Unrecognized remote plugin message: cannot allocate memory
>
>This usually means that the plugin is either invalid or simply
>needs to be recompiled to support the latest protocol.
>```

This occurs even with the HashiCorp built versions.

**Comment by calvn** [comment]
Can you try to run it without specifying `--cap-add=IPC_LOCK` and with `-e SKIP_SETCAP=true`?

**Comment by BinaryWizard904** [comment]
@calvn, that worked! I was able to configure the plugin when I removed `--cap-add=IPC_LOCK`, added `-e SKIP_SETCAP=true`, and disabled mlock in the vault configuration file via `disable_mlock = true`.  Of course that strongly limits the kinds of storage backends I can safely use, but at least Raft is available.
