### ISSUE TITLE
Invalid database version error 

### ISSUE THREAD

**Issue by jgnyshptl** [hashicorp/vault-plugin-database-oracle#49]
I  got an error while writing to the Oracle database plugin. Most likely, it is due to database and client version mismatch. I was able to connect to the PDB database without any issue using SQL*PLUS. Do I need to built plugin using 19.7 client  for the  target database version 19.7  ? 

vault write database/config/oracle plugin_name \
    vault-plugin-database-oracle \
    allowed_roles="*" \
    connection_url='{{username}}/{{password}}@//localhost:1521/xx' \
    username='vaulxxtadmin' \
    password="xxx"

Error writing data to database/config/oracle: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/oracle
Code: 400. Errors:

* error creating database object: invalid database version: 2 errors occurred:
        * checksums did not match
        * checksums did not match

**Comment by pcman312** [comment]
Hi @jgnyshptl ! Can you share the command you used to register the plugin? I suspect the checksum generated from the plugin file may be incorrect.

**Comment by mjtice** [comment]
I ran into a similar issue as well.
1. Make sure you're using the correct version of the plugin.  For vault releases < 1.6 make sure you use the oracle-plugin < 0.3.
2. For a 19c database use the v.19 instant client.
3. If you're swapping oracle-plugin versions then [make sure you reload the backend](https://support.hashicorp.com/hc/en-us/articles/115015431448-Plugin-Replacement-and-Upgrade).

**Comment by fairclothjm** [comment]
hi @jgnyshptl this error occurs if the plugin binary is swapped out without re-registering. Please see the above comment and also make sure to [register the plugin](https://www.vaultproject.io/docs/commands/plugin/register).

**Comment by hw19850907** [comment]
I also meet this problem, but I can't solve this problem by using the above methods

**Comment by hw19850907** [comment]
> I ran into a similar issue as well.
> 
> 1. Make sure you're using the correct version of the plugin.  For vault releases < 1.6 make sure you use the oracle-plugin < 0.3.
> 2. For a 19c database use the v.19 instant client.
> 3. If you're swapping oracle-plugin versions then [make sure you reload the backend](https://support.hashicorp.com/hc/en-us/articles/115015431448-Plugin-Replacement-and-Upgrade).

Vault v1.11.3 (17250b25303c6418c283c95b1d5a9c9f16174fe8) this is my vault version
and my oracle-plugin is 
1808fea9c483a8e6582e56ca6e729480fbd8492d3bcc791f777066c8d602608b  vault-plugin-database-oracle_0.2.2_linux_amd64.zip
```
(test) root@gjzq-sh-mb:~# vault plugin list
Plugins
-------
ad
alicloud
app-id
approle
aws
azure
cassandra
cassandra-database-plugin
centrify
cert
cf
consul
couchbase-database-plugin
elasticsearch-database-plugin
gcp
gcpkms
github
hana-database-plugin
influxdb-database-plugin
jwt
kerberos
kubernetes
kv
ldap
mongodb
mongodb-database-plugin
mongodbatlas
mongodbatlas-database-plugin
mssql
mssql-database-plugin
mysql
mysql-aurora-database-plugin
mysql-database-plugin
mysql-legacy-database-plugin
mysql-rds-database-plugin
nomad
oci
oidc
okta
openldap
pcf
pki
postgresql
postgresql-database-plugin
rabbitmq
radius
redshift-database-plugin
snowflake-database-plugin
ssh
terraform
totp
transit
userpass
vault-plugin-database-oracle
(test) root@gjzq-sh-mb:~# vault write database/config/my-oracle-database     plugin_name=vault-plugin-database-oracle     connection_url="{{username}}/{{password}}@172.28.102.150:1521/bop" allowed_roles="my-role"     username="VAUIT_ADMIN"     password="Huang_Dbd_0926"
Error writing data to database/config/my-oracle-database: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/my-oracle-database
Code: 400. Errors:

* error creating database object: invalid database version: 2 errors occurred:
	* checksums did not match
	* checksums did not match



```
