### ISSUE TITLE
How to use oracle function for rotation_statements?

### ISSUE THREAD

**Issue by os-learner** [hashicorp/vault-plugin-database-oracle#50]
Hello,
Our DBA's want to provide a function that can be used to change passwords instead of giving "Alter Priviliges" to the vault "root" account. 
We tried using the following command. 
select xxxx.change_password("{{name}}",'{{password}}') from dual;

vault write command issues the following error. 

Error writing data to database/static-roles/testrole: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/static-roles/testrole
Code: 500. Errors:

* 1 error occurred:
        * error setting credentials: rpc error: code = Unknown desc = unable to execute rotation query [select GZPLOCL.change_password("{{name}}",'{{password}}') from dual]: ORA-24374: define not done before fetch or execute and fetch

So the question is, do we have to use just "alter user" or can we use an oracle package/ oracle sproc or oracle function ? 
If so, how can I pass the username and password as parameters ?

Please advise.

**Comment by os-learner** [comment]
Update on 3/5/2021 3:49 PM
We tried using SPROC as below and it is also throwing errors.
begin xxxxx.p_change_password('xxxxx','test123'); end;
Error writing data to database/rotate-role/jchung: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/rotate-role/jchung
Code: 500. Errors:

* 1 error occurred:
        * error setting credentials: rpc error: code = Unknown desc = unable to execute rotation query [begin xxxxx.p_change_password('xxxxx','test123') end]: ORA-06550: line 1, column 53:
PLS-00103: Encountered the symbol "END" when expecting one of the following:

   := . ( % ;

**Comment by os-learner** [comment]
Can anyone help guys?

**Comment by yogeshnv** [comment]
Provide the rotate statement in base64 encoded format.

 vault write database/static-roles/some-app db_name=some-db    rotation_statements=base64encodedstatement  username="user-for-which-password-tobe-rotated" rotation_period=300

The actual rotation statement is something like: ["BEGIN mydba.PKG_USER.change_passwd('user-for-which-password-tobe-rotated','{{password}}'); END;"]

password is generated by vault.

**Comment by fairclothjm** [comment]
We reserve github issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this at [Vault Discuss](https://discuss.hashicorp.com/c/vault/30) .
