### ISSUE TITLE
Plugin setup error using vault 1.7.0 (Windows 10 Pro)

### ISSUE THREAD

**Issue by adinath-raveendraraj** [hashicorp/vault-plugin-database-oracle#51]
Hi,

I am running Vault 1.7.0 x64 on Windows 10 Pro, the latest plugin (built from source) and Instant Client v19.10. When I run the vault command:

`vault write database/config/my-db-name connection_url="{{username}}/{{password}}@//my-db-host:1521/my-db-service" allowed_roles="my-db-user-role" username="my-vault-root-user" password="my-vault-root-pwd" plugin_name=oracle-database-plugin
`

I get the following error:
```
Error writing data to database/config/my-db-name: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/my-db-name
Code: 400. Errors:

* error creating database object: invalid database version: 2 errors occurred:
        * exec: "C:\\Program Files\\Hashicorp\\Vault\\plugins\\vault-plugin-database-oracle": file does not exist
        * exec: "C:\\Program Files\\Hashicorp\\Vault\\plugins\\vault-plugin-database-oracle": file does not exist
```
The plug has been placed in the plugins folder and successfully registered using:
```
vault write sys/plugins/catalog/database/oracle-database-plugin sha256="588ff60487aac83c92bc3fd039bdaddc01eb4d1206959a16e7bb34ded3e2b312" command=vault-plugin-database-oracle
```
This is what my config file looks like:
```
storage "file" {
  path = "C:/Program Files/Hashicorp/Vault/data"
}

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}

disable_mlock = true

plugin_directory = "C:/Program Files/Hashicorp/Vault/plugins"

api_addr = "http://127.0.0.1:8200"

```
Has the plugin been tested on Windows? 

To build the plugin I am using go 1.16.3 and mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0 and the Instant Client v19.10 SDK.  

I unsuccessfully tried several things, including using Instant Client 19.3 (same error). I wonder if what I am running into is similar in nature to https://github.com/hashicorp/vault/issues/8009 where the plugin is not able to load the Instant Client libs for some reason.

I am out of ideas, and would love to get this working. Any help is appreciated.

Thanks in advance,

Adi

P.S. The only remarkable issue I ran into while building the plugin was with Go not liking the compiler link flags I put in oci8.pc (I would get "invalid flags --cflags: File"), so ended up having to set the compiler and link flags using env vars (below):

set CGO_CFLAGS=-IC:\oraclient\instantclient_19_10\sdk\include\ -static
set CGO_LDFLAGS=-LC:\oraclient\instantclient_19_10\sdk\lib\msvc\ -loci -static

**Comment by fairclothjm** [comment]
@adinath-raveendraraj Hi,

The `plugin_name` that you used to write your database config does not match the plugin `command` used on registration:

```
vault write database/config/my-db-name \
   plugin_name=oracle-database-plugin \
   ...
```
vs
```
vault write sys/plugins/catalog/database/oracle-database-plugin \
    command=vault-plugin-database-oracle \
    ...
```

Please make sure these are the same and try again. Thanks!

**Comment by fairclothjm** [comment]
We reserve github issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this at [Vault Discuss](https://discuss.hashicorp.com/c/vault/30) .
