### ISSUE TITLE
Incompatible API version with plugin. Plugin version: 5, Client versions: [3 4]

### ISSUE THREAD

**Issue by iridian-ks** [hashicorp/vault-plugin-database-oracle#58]
We're running Vault version 1.7.1 and we have the latest version of the Oracle plugin version 0.4.1.

I tried searching the repo to see where the plugin version stuff is set or how it works. I can go in and update things but it's not clear where or what is going on.

I am assuming this means the Vault server supports only plugin version 5 and the vault oracle plugin supports versions 3 and 4 but not 5. It seems like Vault is a client of the plugin but maybe not. The error seems ambiguous.

Seeing as how Vault version 1.7 is not reverse compatible with older versions of Vault. We are now stuck in a broken state.

Any help is greatly appreciated.

**Comment by pcman312** [comment]
Hi @iridian-ks! Apologies for the delayed response.

Where are you seeing this error? Can you provide detailed reproduction steps for this?

**Comment by iridian-ks** [comment]
Actually,  I got it working. It turns out this error is extremely generic and basically if any issue comes up it will throw this error. This creates a very misleading error message that something is out of date and isn't actually very helpful.

For the Vault database plugins there is a hard coded 1 second timeout when communicating with an external process (since that's how the plugin system works). This means if there is any kind of database latency between Vault and Oracle you get this error and turning up the logging level to debug reveals some error messages. Had to line up the error messages with what was in git to find the timeout code and realize that 1 second timeout is not configurable.

Overall very unpleasant experience. It would be nice if error logging was better but obviously difficult since you lose a lot of context once requests go out-of-process. The hard coded non-configurable timeout is also less than ideal, but that code is located in Vault proper and not the plugin.

**Comment by pcman312** [comment]
@iridian-ks 
> For the Vault database plugins there is a hard coded 1 second timeout when communicating with an external process

Can you point me to where this is? This shouldn't be the issue because what you described is Vault talking with the external plugin process, not the plugin talking with Oracle. The versioning error you mentioned is likely due to the refactor that happened in the database engine in Vault when 1.7 came out. However, Vault has been tested with both old versions of this plugin and new versions so I'm unsure exactly how you were able to get that error.
