### ISSUE TITLE
Cannot read wallets from wallet_location

### ISSUE THREAD

**Issue by SHINICHI-ANDO** [hashicorp/vault-plugin-database-oracle#66]
Hi Team.

I use this connection_url

`connection_url='{{username}}/{{password}}@tcps://~omit~&wallet_location="/etc/vault.d/wallets"'`

but vault read wallets(cwallet.sso, ewallet.p12) from /etc/ORACLE/WALLETS/vault.

I want use other wallet_location in each connections.
How can I set it?

My environment : 
- OS : Oracle Linux
- vault oss 1.8.2
- vault-plugin-database-oracle 0.4.2
- install oracle-instantclient-release-el8
- install oracle-instantclient-basic
- Oracle Database is Autonomous Database on OCI

**Comment by fairclothjm** [comment]
@SHINICHI-ANDO Hi,
You should be able to provide this in the sqlnet.ora
```
WALLET_LOCATION = (SOURCE = (METHOD = FILE) (METHOD_DATA = (DIRECTORY = /opt/oracle/ssl_wallet)))
...
```

**Comment by fairclothjm** [comment]
We reserve github issues for bug reports and feature requests, which this doesn't appear to be. As such, I'm going to close this and suggest that you ask about this at [Vault Discuss](https://discuss.hashicorp.com/c/vault/30) .
