### ISSUE TITLE
Oracle plugin with RDS

### ISSUE THREAD

**Issue by jordzn** [hashicorp/vault-plugin-database-oracle#7]
Hi,

Attempting to configure Vault to create dynamic Oracle creds in an AWS RDS database with this plugin, but I'm hitting an error that I can't figure out.

It's worth noting that I'm able to successfully log into the RDS DB from the Vault box.

The plugin has been placed at `/etc/vault/plugins/vault-plugin-database-oracle` and is exectutable, owned by root.

The plugins directory has been configured, as shown below:
```
backend "consul" {
  address = "xxx.xx.xx.xxx:8500"
  scheme = "http"
  path = "vault-ha/"
}

plugin_directory="/etc/vault/plugins"
disable_mlock=true

listener "tcp" {
  address     = "127.0.0.1:8200"
  tls_disable = 1
}
```

Steps taken so far:
1. `vault auth {root_token}`
2. `vault mount database`
3. `sha256sum /etc/vault/plugins/vault-plugin-database-oracle`
4. 
```
vault write sys/plugins/catalog/oracle-database-plugin \
sha256=69d312029f0dbd07d629d14231e15512ed6ca92960a0f15fd0591dd060ce71b2 \
command="vault-plugin-database-oracle"
```

All successful up until this point. The error comes when running:

```
[root@ip-xxx-xx-xx-xxx plugins]# vault write database/config/oracle plugin_name=oracle-database-plugin connection_url="admin/pass@aws-rds-dns-name-here.eu-west-1.rds.amazonaws.com:1521" allowed_roles="readonly"
**Error writing data to database/config/oracle: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/oracle
Code: 400. Errors:

* error creating database object: fork/exec /etc/vault/plugins/vault-plugin-database-oracle: exec format error**
**
```

Would it be possible to give some insight around this error please? 

Thanks in advance.

**Comment by Niranjankolli** [comment]
How did you resolve this?
Encountered similar issue. Please help.
