### ISSUE TITLE
Build new release from tag v0.5.1

### ISSUE THREAD

**Issue by faelp22** [hashicorp/vault-plugin-database-oracle#72]
Hello everyone, I would like to know if the new release version will be released soon from Tag v0.5.1 or if I can build it right here on my machine.

**Comment by austingebauer** [comment]
Hi, @faelp22! We plan to release the next version of the plugin soon. You can certainly build the plugin, but I'd suggest to wait for the official release.

**Comment by faelp22** [comment]
Hi @austingebauer , thanks for replying, I tried to build it through [make build-in-container], but it's giving an error, in this case I'll wait for the release.

![image](https://user-images.githubusercontent.com/6642575/146091491-3c8bd9c8-c8f1-4c45-8ec9-eb362bd5bdf1.png)

If it's not too inconvenient, would there be roughly a date when it will be released?

**Comment by austingebauer** [comment]
@faelp22 - We're planning to get a release out by end of week. I'll update you here if we're not able to achieve that for some reason.

**Comment by austingebauer** [comment]
Absolutely, @faelp22! We've just published v0.5.1 of the plugin at https://releases.hashicorp.com/vault-plugin-database-oracle. I'm going to close this issue now.
