### ISSUE TITLE
revocation?

### ISSUE THREAD

**Issue by dmlond** [hashicorp/vault-plugin-database-oracle#8]
I am new to using the hashicorp vault database backend in general, so please excuse this if there is something that I am doing wrong.

I am working with a local dockerized vault and oracle database (using the official docker store oracle 12c database, and running a vault server within the official docker store oracle instantclient image so it has access to instantclient).

I am able to register the plugin, and create a database/config
```
vault mount database
expected_sha=`shasum -a 256 vault/plugins/vault-plugin-database-oracle  | cut -d' ' -f1`
vault write sys/plugins/catalog/vault-plugin-database-oracle sha_256=${expected_sha} command="vault-plugin-database-oracle"
vault write database/config/sps \
    plugin_name=vault-plugin-database-oracle \
    connection_url="vault/abc123@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oradb)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ORCLPDB1.localdomain)))" \
    allowed_roles="vault_managed_admin_user"

```
I can create a role that creates a user and read the creds for that user to get a valid user to use to access the db.
```
vault write database/roles/vault_managed_admin_user \
    db_name=sps \
    creation_statements="CREATE USER {{name}} IDENTIFIED BY {{password}} DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;GRANT CONNECT TO {{name}};GRANT CREATE SESSION TO {{name}};GRANT UNLIMITED TABLESPACE TO {{name}};GRANT DELETE, INSERT, SELECT, UPDATE ON seemee TO {{name}};" \
    default_ttl="120" \
    max_ttl="120"
vault read database/creds/vault_managed_admin_user
Key            	Value
---            	-----
lease_id       	database/creds/vault_managed_admin_user/7e2ecf75-da1f-59d4-0827-2fababe2d64c
lease_duration 	768h0m0s
lease_renewable	true
password       	A1a_3xxxv95w9rs1u6z6
username       	v_root_vault_ma_q2s42y4rupz1r7
docker-compose exec oradb bash -c 'source /home/oracle/.bashrc; /u01/app/oracle/product/12.2.0/dbhome_1/bin/sqlplus v_root_vault_ma_q2s42y4rupz1r7/A1a_3xxxv95w9rs1u6z6@ORCLPDB1'
SQL> select * from VAULT.seemee;

	ID
----------
NAME
--------------------------------------------------------------------------------
	 1
SEEN
```

The problem is that the revocation does not work.  I can see the following in the vault logs
```
2017/10/02 14:19:00.535452 [ERROR] expiration: failed to revoke lease: lease_id=database/creds/vault_managed_admin_user/7e2ecf75-da1f-59d4-0827-2fababe2d64c error=failed to revoke entry: resp:(*logical.Response)(nil) err:ORA-00942: table or view does not exist
```

I also see that when I try to manually revoke the cred with the lease_id
```
vault revoke database/creds/vault_managed_admin_user/7e2ecf75-da1f-59d4-0827-2fababe2d64c
Revoke error: Error making API request.

URL: PUT http://0.0.0.0:8200/v1/sys/leases/revoke/database/creds/vault_managed_admin_user/7e2ecf75-da1f-59d4-0827-2fababe2d64c
Code: 400. Errors:

* failed to revoke entry: resp:(*logical.Response)(nil) err:ORA-00942: table or view does not exist
```

I am not sure how to find out the SQL that the revocation is attempting to run, but it does not appear to be attempting to run the default revocationSQL, which I am pretty sure (if I understand oracle.go) is
```
REVOKE CONNECT FROM {{name}};
REVOKE CREATE SESSION FROM {{name}};
DROP USER {{name}};
```

I am using the precompiled binary release v0.1.1.

**Comment by briankassouf** [comment]
Hi @dmlond,

I'm not exactly sure what the issue is, but could you try configuring a custom revocation statement that uses the same TABLESPACE settings as your creation statement? 

To set a revocation statement during role configuration set the `revocation_statement="..."` flag

**Comment by dmlond** [comment]
I am not sure how to do this. The oracle DROP USER commands allow me to CASCADE, which drops any tables in the user tablespace. Are you saying drop the tablespace?

One thing to note, I can manually login to the oracle database with the vault user, and run the statements
```
REVOKE CONNECT FROM user;
REVOKE CREATE SESSION FROM {{name}};
DROP USER user;
```
and it drops the user. I am not sure why vault would be able to connect as the vault user and run the creation_statements, but not the revocation_statements.

**Comment by briankassouf** [comment]
No i didn't mean drop the tables, I thought maybe `DEFAULT TABLESPACE USERS ...` was storing the user data in a non-default location. Sometimes when a creation statement is using additional SQL the revocation statement needs to be updated as well. 

When running the Revocation statements all vault does is connect to the db (using the same connection data as creating the user) and run the statements one by one, replacing `{{name}}` with the username. If they are working when you run them by hand, i'm not sure why they wouldn't be working from within vault. Judging by the error message you're seeing it appears the table can't be found. 

Were you able to manually drop a user that vault generated with your creation statement (username like `A1a_....`) with that revocation statement? 

If so, the only other thing I could think of is the plugin uses these two statements to try and kill all active sessions by the user: https://github.com/hashicorp/vault-plugin-database-oracle/blob/master/oracle.go#L32-L34. Perhaps the issue could be coming from there?

**Comment by dmlond** [comment]
ahh. That's where it is happening. I cannot login with sqlplus and `SELECT sid, serial#, username FROM v$session WHERE username = UPPER('{{name}}')`. thanks. I just have to figure out how to fix this now.

**Comment by dmlond** [comment]
You can close this issue (I didnt think that I should close it). Thanks so much for your help. I had to
```
CREATE ROLE SESSION_ROLE;
GRANT SELECT ON v_$session TO SESSION_ROLE;
GRANT SESSION_ROLE TO VAULT;
```

**Comment by briankassouf** [comment]
Glad it was solved!
