### ISSUE TITLE
Q:vault-plugin-database-oracle on Mac M1 (ARM)

### ISSUE THREAD

**Issue by andytael** [hashicorp/vault-plugin-database-oracle#86]
Will the vault-plugin-database-oracle work on a Mac M1 (ARM processor)?

Thanks
Andy

**Comment by tomhjp** [comment]
Hi @andytael, we haven't tested that but I doubt we'd try to officially support it without native support for the Instant Client library first: https://www.oracle.com/database/technologies/instant-client/downloads.html. (Reference on that setup requirement [here](https://www.vaultproject.io/docs/secrets/databases/oracle#setup))

**Comment by plafue** [comment]
Instant client is available now for arm64:
https://www.oracle.com/database/technologies/instant-client/macos-arm64-downloads.html
