### ISSUE TITLE
Invalid database version

### ISSUE THREAD

**Issue by slicutium** [hashicorp/vault-plugin-database-oracle#90]
I am trying to use the plugin to connect to an Oracle database 12c Release 12.1.0.1.0

Vault is runing in a Debian 11 server, config file as follows:

storage "file" {
  path    = "/etc/vault/data"
}

listener "tcp" {
  address     = "<<SERVER ADDRESS>>:8200"
  tls_disable = "true"   <<<<<<until a certificate is provided
}

disable_mlock = true
plugin_directory = "/etc/vault/plugins"
api_addr = "http://<<SERVER ADDRESS>>:8200"
cluster_addr = "https://<<SERVER ADDRESS>>:8201"
ui = true

latest version of the plugin downloaded and  registered as follows:

vault write sys/plugins/catalog/database/vault-plugin-database-oracle \
> sha256=b17856c5465dd687f2b1805ec3b7b18facaffd82073ba05bb12120b965a3285d command="vault-plugin-database-oracle"
Success! Data written to: sys/plugins/catalog/database/vault-plugin-database-oracle

When trying to set the connection with
vault write database/config/my-oracle-database \
>     plugin_name=vault-plugin-database-oracle  \
>     connection_url='{{username}}/{{password}}@<<redacteDBinformation>> \
>     allowed_roles='my-role' \
>     username=<redacted> \
>     password=<redacted>

get the following error:

Error writing data to database/config/my-oracle-database: Error making API request.

URL: PUT http://<serveraddress>:8200/v1/database/config/my-oracle-database
Code: 400. Errors:

* error creating database object: invalid database version: 2 errors occurred:
        * Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
        * Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

I have checked all over and disabled mlock after finding some post stating that it could solve the problem. Still not able to solve the issue.

Will greatly appreciate any help.

**Comment by fairclothjm** [comment]
The oracle binary from [the releases page](https://releases.hashicorp.com/vault-plugin-database-oracle/) is built with Oracle Instant Client SDK 19.3. You may need to recompile the plugin for your version (12).

**Comment by slicutium** [comment]
Thank you for the response, we built the plugin using Oracle instantclient 12.1 steps as follow

echo $LD_LIBRARY_PATH
/opt/oracle/instantclient_12_1

echo $PKG_CONFIG_PATH
/usr/lib/pkgconfig

cat /usr/lib/pkgconfig/oci8.pc
version=12.1

libdir=/opt/oracle/instantclient_12_1
includedir=/usr/include/oracle/12.1

build=client64

Name: oci8
Description: Oracle database engine
Version: ${version}
Libs: -L${libdir} -libclntsh.so
Cflags: -I${includedir}

pkg-config --libs oci8
-L/opt/oracle/instantclient_12_1 -libclntsh.so


ls /opt/oracle/instantclient_12_1/
adrci  BASIC_README  genezi  libclntshcore.so.12.1  libclntsh.so  libclntsh.so.12.1  libipc1.so  libmql1.so  libnnz12.so  libocci.so  libocci.so.12.1  libociei.so  libocijdbc12.so  libons.so  liboramysql12.so  ojdbc6.jar  ojdbc7.jar  uidrvci  xstreams.jar

pkg-config --cflags oci8
-I/usr/include/oracle/12.1

ls /usr/include/oracle/12.1
ldap.h  nzerror.h  nzt.h  occiAQ.h  occiCommon.h  occiControl.h  occiData.h  occi.h  occiObjects.h  oci1.h  oci8dp.h  ociap.h  ociapr.h  ocidef.h  ocidem.h  ocidfn.h  ociextp.h  oci.h  ocikpr.h  ocixmldb.h  ocixstream.h  odci.h  oratypes.h  orid.h  ori.h  orl.h  oro.h  ort.h  xa.h

go build -o vault-plugin-database-oracle ./plugin

sha256sum vault-plugin-database-oracle 
678f560656a79862b6506c4ac95a3f4737f43371eb788bee70a486ab479492d9  vault-plugin-database-oracle

sudo cp vault-plugin-database-oracle /etc/vault/plugins/vault-plugin-database-oracle 

After database is enabled and the plugin is registered with vault

The next step (setting up db connection) fails with the same error as before:

Error writing data to database/config/my-oracle-database: Error making API request.

URL: PUT http://redacted:8200/v1/database/config/my-oracle-database
Code: 400. Errors:

error creating database object: invalid database version: 2 errors occurred:
* Unrecognized remote plugin message:
This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
* Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.


While trying to run "make test"
I get the following message
==> Checking that code complies with gofmt requirements...
go generate 
CGO_ENABLED=1 go test -tags='' $(go list ./... | grep -v /vendor/ | grep -v /integ)  -timeout=20m -parallel=4
ok      github.com/hashicorp/vault-plugin-database-oracle       (cached)
?       github.com/hashicorp/vault-plugin-database-oracle/plugin        [no test files]

At this point I am all out of ideas on how to troubleshoot this.
Will appreciate any suggestions.

**Comment by fairclothjm** [comment]
@slicutium 

- What is the Vault server version?
- Can you provide DEBUG level vault server logs?

**Comment by slicutium** [comment]
@fairclothjm 
Thank you, checking the debug logs for vault server we discovered that vault was not able to find the library "libclntsh.so.12.1". Even though the library was used to build the plugin on our end, and the path had its location, vault was looking for it specifically in /usr/lib/
We moved the library to its rightful location and the issue was fixed.
Again, thank you for the help.

**Comment by fairclothjm** [comment]
@slicutium Happy to help! 😄
