### ISSUE TITLE
Hashi Vault 1.12.x Oracle 0.7.0 Registration Failed

### ISSUE THREAD

**Issue by dw-develop** [hashicorp/vault-plugin-database-oracle#98]
When upgrading to latest version of Hashi Vault the current Oracle Engine plugin 0.7.0 will not register showing the following error below on Hashi Vault 1.12.x versions. I tested this by rolling back to a few versions of 1.11.x below.

Vault Version Page: https://releases.hashicorp.com/vault/

Oracle Plugin Download: https://releases.hashicorp.com/vault-plugin-database-oracle/
Using 0.7.0

The 0.7.0 will register on versions 1.11.3 to 1.11.5-1.

vault plugin register \
    -sha256="<sha>" \
    -version=v0.7.0 \
    database \
    vault-plugin-database-oracle_0.7.0

2022-11-03T21:29:00.024Z [ERROR] plugin process exited: metadata=true path=/root/vault/plugins/vault-plugin-database-oracle_0.7.0 pid=3648 error="exit status 127"
2022-11-03T21:29:00.073Z [WARN]  core: Error determining plugin version:
  error=
  | 2 errors occurred:
  |     * failed to load plugin as database v5: Unrecognized remote plugin message: 
  | 
  | This usually means that the plugin is either invalid or simply
  | needs to be recompiled to support the latest protocol.
  |     * failed to load plugin as database v4: Unrecognized remote plugin message: 
  | 
  | This usually means that the plugin is either invalid or simply
  | needs to be recompiled to support the latest protocol.
  |

**Comment by fairclothjm** [comment]
We will close this issue as it was resolved with the customer internally. Please feel free to reopen if you feel this was a mistake, or if there is additional information to add. Thanks!
